[workspace]
members = ["ipld/resolver"]

[workspace.package]
authors = ["Protocol Labs"]
edition = "2021"
license-file = "LICENSE"

[workspace.dependencies]
anyhow = "1.0"
base64 = "0.21.0"
lazy_static = "1.4"
log = "0.4"
env_logger = "0.10"
prometheus = "0.13"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.16", features = ["full"] }
thiserror = "1.0.38"
quickcheck = "1"
quickcheck_macros = "1"
blake2b_simd = "1.0"
rand = "0.8"
serde_json = { version = "1.0.91", features = ["raw_value"] }

fvm_ipld_blockstore = "0.1"
fvm_ipld_encoding = "0.3"
fvm_shared = { version = "=3.0.0-alpha.17", default-features = false, features = ["crypto"] }
ipc-sdk = { git = "https://github.com/consensus-shipyard/ipc-actors.git", tag = "v0.2.0" }
libipld = { version = "0.14", default-features = false, features = ["dag-cbor"] }
